/* Auto-generated stub — DTrace disabled for Wasm build */
#define VBOXVMM_EM_FF_ALL(...) do { } while (0)
#define VBOXVMM_EM_FF_ALL_ENABLED() (0)
#define VBOXVMM_EM_FF_ALL_RET(...) do { } while (0)
#define VBOXVMM_EM_FF_ALL_RET_ENABLED() (0)
#define VBOXVMM_EM_FF_HIGH(...) do { } while (0)
#define VBOXVMM_EM_FF_HIGH_ENABLED() (0)
#define VBOXVMM_EM_FF_RAW(...) do { } while (0)
#define VBOXVMM_EM_FF_RAW_ENABLED() (0)
#define VBOXVMM_EM_FF_RAW_RET(...) do { } while (0)
#define VBOXVMM_EM_FF_RAW_RET_ENABLED() (0)
#define VBOXVMM_EM_RAW_RUN_PRE(...) do { } while (0)
#define VBOXVMM_EM_RAW_RUN_PRE_ENABLED() (0)
#define VBOXVMM_EM_RAW_RUN_RET(...) do { } while (0)
#define VBOXVMM_EM_RAW_RUN_RET_ENABLED() (0)
#define VBOXVMM_EM_STATE_CHANGED(...) do { } while (0)
#define VBOXVMM_EM_STATE_CHANGED_ENABLED() (0)
#define VBOXVMM_EM_STATE_UNCHANGED(...) do { } while (0)
#define VBOXVMM_EM_STATE_UNCHANGED_ENABLED() (0)
#define VBOXVMM_EXIT_CPUID(...) do { } while (0)
#define VBOXVMM_EXIT_CPUID_ENABLED() (0)
#define VBOXVMM_EXIT_CRX_READ(...) do { } while (0)
#define VBOXVMM_EXIT_CRX_READ_ENABLED() (0)
#define VBOXVMM_EXIT_CRX_WRITE(...) do { } while (0)
#define VBOXVMM_EXIT_CRX_WRITE_ENABLED() (0)
#define VBOXVMM_EXIT_DRX_READ(...) do { } while (0)
#define VBOXVMM_EXIT_DRX_READ_ENABLED() (0)
#define VBOXVMM_EXIT_DRX_WRITE(...) do { } while (0)
#define VBOXVMM_EXIT_DRX_WRITE_ENABLED() (0)
#define VBOXVMM_EXIT_GETSEC(...) do { } while (0)
#define VBOXVMM_EXIT_GETSEC_ENABLED() (0)
#define VBOXVMM_EXIT_HALT(...) do { } while (0)
#define VBOXVMM_EXIT_HALT_ENABLED() (0)
#define VBOXVMM_EXIT_INVD(...) do { } while (0)
#define VBOXVMM_EXIT_INVD_ENABLED() (0)
#define VBOXVMM_EXIT_INVLPG(...) do { } while (0)
#define VBOXVMM_EXIT_INVLPG_ENABLED() (0)
#define VBOXVMM_EXIT_LGDT(...) do { } while (0)
#define VBOXVMM_EXIT_LGDT_ENABLED() (0)
#define VBOXVMM_EXIT_LIDT(...) do { } while (0)
#define VBOXVMM_EXIT_LIDT_ENABLED() (0)
#define VBOXVMM_EXIT_LLDT(...) do { } while (0)
#define VBOXVMM_EXIT_LLDT_ENABLED() (0)
#define VBOXVMM_EXIT_LTR(...) do { } while (0)
#define VBOXVMM_EXIT_LTR_ENABLED() (0)
#define VBOXVMM_EXIT_MONITOR(...) do { } while (0)
#define VBOXVMM_EXIT_MONITOR_ENABLED() (0)
#define VBOXVMM_EXIT_MWAIT(...) do { } while (0)
#define VBOXVMM_EXIT_MWAIT_ENABLED() (0)
#define VBOXVMM_EXIT_PAUSE(...) do { } while (0)
#define VBOXVMM_EXIT_PAUSE_ENABLED() (0)
#define VBOXVMM_EXIT_RDMSR(...) do { } while (0)
#define VBOXVMM_EXIT_RDMSR_ENABLED() (0)
#define VBOXVMM_EXIT_RDPMC(...) do { } while (0)
#define VBOXVMM_EXIT_RDPMC_ENABLED() (0)
#define VBOXVMM_EXIT_RDRAND(...) do { } while (0)
#define VBOXVMM_EXIT_RDRAND_ENABLED() (0)
#define VBOXVMM_EXIT_RDSEED(...) do { } while (0)
#define VBOXVMM_EXIT_RDSEED_ENABLED() (0)
#define VBOXVMM_EXIT_RDTSC(...) do { } while (0)
#define VBOXVMM_EXIT_RDTSC_ENABLED() (0)
#define VBOXVMM_EXIT_RDTSCP(...) do { } while (0)
#define VBOXVMM_EXIT_RDTSCP_ENABLED() (0)
#define VBOXVMM_EXIT_RSM(...) do { } while (0)
#define VBOXVMM_EXIT_RSM_ENABLED() (0)
#define VBOXVMM_EXIT_SGDT(...) do { } while (0)
#define VBOXVMM_EXIT_SGDT_ENABLED() (0)
#define VBOXVMM_EXIT_SIDT(...) do { } while (0)
#define VBOXVMM_EXIT_SIDT_ENABLED() (0)
#define VBOXVMM_EXIT_SLDT(...) do { } while (0)
#define VBOXVMM_EXIT_SLDT_ENABLED() (0)
#define VBOXVMM_EXIT_STR(...) do { } while (0)
#define VBOXVMM_EXIT_STR_ENABLED() (0)
#define VBOXVMM_EXIT_SVM_CLGI(...) do { } while (0)
#define VBOXVMM_EXIT_SVM_CLGI_ENABLED() (0)
#define VBOXVMM_EXIT_SVM_STGI(...) do { } while (0)
#define VBOXVMM_EXIT_SVM_STGI_ENABLED() (0)
#define VBOXVMM_EXIT_SVM_VMLOAD(...) do { } while (0)
#define VBOXVMM_EXIT_SVM_VMLOAD_ENABLED() (0)
#define VBOXVMM_EXIT_SVM_VMRUN(...) do { } while (0)
#define VBOXVMM_EXIT_SVM_VMRUN_ENABLED() (0)
#define VBOXVMM_EXIT_SVM_VMSAVE(...) do { } while (0)
#define VBOXVMM_EXIT_SVM_VMSAVE_ENABLED() (0)
#define VBOXVMM_EXIT_TASK_SWITCH(...) do { } while (0)
#define VBOXVMM_EXIT_TASK_SWITCH_ENABLED() (0)
#define VBOXVMM_EXIT_VMM_CALL(...) do { } while (0)
#define VBOXVMM_EXIT_VMM_CALL_ENABLED() (0)
#define VBOXVMM_EXIT_VMX_EPT_MISCONFIG(...) do { } while (0)
#define VBOXVMM_EXIT_VMX_EPT_MISCONFIG_ENABLED() (0)
#define VBOXVMM_EXIT_VMX_EPT_VIOLATION(...) do { } while (0)
#define VBOXVMM_EXIT_VMX_EPT_VIOLATION_ENABLED() (0)
#define VBOXVMM_EXIT_VMX_INVEPT(...) do { } while (0)
#define VBOXVMM_EXIT_VMX_INVEPT_ENABLED() (0)
#define VBOXVMM_EXIT_VMX_INVPCID(...) do { } while (0)
#define VBOXVMM_EXIT_VMX_INVPCID_ENABLED() (0)
#define VBOXVMM_EXIT_VMX_INVVPID(...) do { } while (0)
#define VBOXVMM_EXIT_VMX_INVVPID_ENABLED() (0)
#define VBOXVMM_EXIT_VMX_VAPIC_ACCESS(...) do { } while (0)
#define VBOXVMM_EXIT_VMX_VAPIC_ACCESS_ENABLED() (0)
#define VBOXVMM_EXIT_VMX_VAPIC_WRITE(...) do { } while (0)
#define VBOXVMM_EXIT_VMX_VAPIC_WRITE_ENABLED() (0)
#define VBOXVMM_EXIT_VMX_VMCLEAR(...) do { } while (0)
#define VBOXVMM_EXIT_VMX_VMCLEAR_ENABLED() (0)
#define VBOXVMM_EXIT_VMX_VMFUNC(...) do { } while (0)
#define VBOXVMM_EXIT_VMX_VMFUNC_ENABLED() (0)
#define VBOXVMM_EXIT_VMX_VMLAUNCH(...) do { } while (0)
#define VBOXVMM_EXIT_VMX_VMLAUNCH_ENABLED() (0)
#define VBOXVMM_EXIT_VMX_VMPTRLD(...) do { } while (0)
#define VBOXVMM_EXIT_VMX_VMPTRLD_ENABLED() (0)
#define VBOXVMM_EXIT_VMX_VMPTRST(...) do { } while (0)
#define VBOXVMM_EXIT_VMX_VMPTRST_ENABLED() (0)
#define VBOXVMM_EXIT_VMX_VMREAD(...) do { } while (0)
#define VBOXVMM_EXIT_VMX_VMREAD_ENABLED() (0)
#define VBOXVMM_EXIT_VMX_VMRESUME(...) do { } while (0)
#define VBOXVMM_EXIT_VMX_VMRESUME_ENABLED() (0)
#define VBOXVMM_EXIT_VMX_VMWRITE(...) do { } while (0)
#define VBOXVMM_EXIT_VMX_VMWRITE_ENABLED() (0)
#define VBOXVMM_EXIT_VMX_VMXOFF(...) do { } while (0)
#define VBOXVMM_EXIT_VMX_VMXOFF_ENABLED() (0)
#define VBOXVMM_EXIT_VMX_VMXON(...) do { } while (0)
#define VBOXVMM_EXIT_VMX_VMXON_ENABLED() (0)
#define VBOXVMM_EXIT_WBINVD(...) do { } while (0)
#define VBOXVMM_EXIT_WBINVD_ENABLED() (0)
#define VBOXVMM_EXIT_WRMSR(...) do { } while (0)
#define VBOXVMM_EXIT_WRMSR_ENABLED() (0)
#define VBOXVMM_EXIT_XRSTORS(...) do { } while (0)
#define VBOXVMM_EXIT_XRSTORS_ENABLED() (0)
#define VBOXVMM_EXIT_XSAVES(...) do { } while (0)
#define VBOXVMM_EXIT_XSAVES_ENABLED() (0)
#define VBOXVMM_EXIT_XSETBV(...) do { } while (0)
#define VBOXVMM_EXIT_XSETBV_ENABLED() (0)
#define VBOXVMM_INSTR_CPUID(...) do { } while (0)
#define VBOXVMM_INSTR_CPUID_ENABLED() (0)
#define VBOXVMM_INSTR_CRX_READ(...) do { } while (0)
#define VBOXVMM_INSTR_CRX_READ_ENABLED() (0)
#define VBOXVMM_INSTR_CRX_WRITE(...) do { } while (0)
#define VBOXVMM_INSTR_CRX_WRITE_ENABLED() (0)
#define VBOXVMM_INSTR_DRX_READ(...) do { } while (0)
#define VBOXVMM_INSTR_DRX_READ_ENABLED() (0)
#define VBOXVMM_INSTR_DRX_WRITE(...) do { } while (0)
#define VBOXVMM_INSTR_DRX_WRITE_ENABLED() (0)
#define VBOXVMM_INSTR_GETSEC(...) do { } while (0)
#define VBOXVMM_INSTR_GETSEC_ENABLED() (0)
#define VBOXVMM_INSTR_HALT(...) do { } while (0)
#define VBOXVMM_INSTR_HALT_ENABLED() (0)
#define VBOXVMM_INSTR_INVD(...) do { } while (0)
#define VBOXVMM_INSTR_INVD_ENABLED() (0)
#define VBOXVMM_INSTR_INVLPG(...) do { } while (0)
#define VBOXVMM_INSTR_INVLPG_ENABLED() (0)
#define VBOXVMM_INSTR_LGDT(...) do { } while (0)
#define VBOXVMM_INSTR_LGDT_ENABLED() (0)
#define VBOXVMM_INSTR_LIDT(...) do { } while (0)
#define VBOXVMM_INSTR_LIDT_ENABLED() (0)
#define VBOXVMM_INSTR_LLDT(...) do { } while (0)
#define VBOXVMM_INSTR_LLDT_ENABLED() (0)
#define VBOXVMM_INSTR_LTR(...) do { } while (0)
#define VBOXVMM_INSTR_LTR_ENABLED() (0)
#define VBOXVMM_INSTR_MONITOR(...) do { } while (0)
#define VBOXVMM_INSTR_MONITOR_ENABLED() (0)
#define VBOXVMM_INSTR_MWAIT(...) do { } while (0)
#define VBOXVMM_INSTR_MWAIT_ENABLED() (0)
#define VBOXVMM_INSTR_PAUSE(...) do { } while (0)
#define VBOXVMM_INSTR_PAUSE_ENABLED() (0)
#define VBOXVMM_INSTR_RDMSR(...) do { } while (0)
#define VBOXVMM_INSTR_RDMSR_ENABLED() (0)
#define VBOXVMM_INSTR_RDPMC(...) do { } while (0)
#define VBOXVMM_INSTR_RDPMC_ENABLED() (0)
#define VBOXVMM_INSTR_RDRAND(...) do { } while (0)
#define VBOXVMM_INSTR_RDRAND_ENABLED() (0)
#define VBOXVMM_INSTR_RDSEED(...) do { } while (0)
#define VBOXVMM_INSTR_RDSEED_ENABLED() (0)
#define VBOXVMM_INSTR_RDTSC(...) do { } while (0)
#define VBOXVMM_INSTR_RDTSC_ENABLED() (0)
#define VBOXVMM_INSTR_RDTSCP(...) do { } while (0)
#define VBOXVMM_INSTR_RDTSCP_ENABLED() (0)
#define VBOXVMM_INSTR_RSM(...) do { } while (0)
#define VBOXVMM_INSTR_RSM_ENABLED() (0)
#define VBOXVMM_INSTR_SGDT(...) do { } while (0)
#define VBOXVMM_INSTR_SGDT_ENABLED() (0)
#define VBOXVMM_INSTR_SIDT(...) do { } while (0)
#define VBOXVMM_INSTR_SIDT_ENABLED() (0)
#define VBOXVMM_INSTR_SLDT(...) do { } while (0)
#define VBOXVMM_INSTR_SLDT_ENABLED() (0)
#define VBOXVMM_INSTR_STR(...) do { } while (0)
#define VBOXVMM_INSTR_STR_ENABLED() (0)
#define VBOXVMM_INSTR_SVM_CLGI(...) do { } while (0)
#define VBOXVMM_INSTR_SVM_CLGI_ENABLED() (0)
#define VBOXVMM_INSTR_SVM_STGI(...) do { } while (0)
#define VBOXVMM_INSTR_SVM_STGI_ENABLED() (0)
#define VBOXVMM_INSTR_SVM_VMLOAD(...) do { } while (0)
#define VBOXVMM_INSTR_SVM_VMLOAD_ENABLED() (0)
#define VBOXVMM_INSTR_SVM_VMRUN(...) do { } while (0)
#define VBOXVMM_INSTR_SVM_VMRUN_ENABLED() (0)
#define VBOXVMM_INSTR_SVM_VMSAVE(...) do { } while (0)
#define VBOXVMM_INSTR_SVM_VMSAVE_ENABLED() (0)
#define VBOXVMM_INSTR_VMM_CALL(...) do { } while (0)
#define VBOXVMM_INSTR_VMM_CALL_ENABLED() (0)
#define VBOXVMM_INSTR_VMX_INVEPT(...) do { } while (0)
#define VBOXVMM_INSTR_VMX_INVEPT_ENABLED() (0)
#define VBOXVMM_INSTR_VMX_INVPCID(...) do { } while (0)
#define VBOXVMM_INSTR_VMX_INVPCID_ENABLED() (0)
#define VBOXVMM_INSTR_VMX_INVVPID(...) do { } while (0)
#define VBOXVMM_INSTR_VMX_INVVPID_ENABLED() (0)
#define VBOXVMM_INSTR_VMX_VMCLEAR(...) do { } while (0)
#define VBOXVMM_INSTR_VMX_VMCLEAR_ENABLED() (0)
#define VBOXVMM_INSTR_VMX_VMFUNC(...) do { } while (0)
#define VBOXVMM_INSTR_VMX_VMFUNC_ENABLED() (0)
#define VBOXVMM_INSTR_VMX_VMLAUNCH(...) do { } while (0)
#define VBOXVMM_INSTR_VMX_VMLAUNCH_ENABLED() (0)
#define VBOXVMM_INSTR_VMX_VMPTRLD(...) do { } while (0)
#define VBOXVMM_INSTR_VMX_VMPTRLD_ENABLED() (0)
#define VBOXVMM_INSTR_VMX_VMPTRST(...) do { } while (0)
#define VBOXVMM_INSTR_VMX_VMPTRST_ENABLED() (0)
#define VBOXVMM_INSTR_VMX_VMREAD(...) do { } while (0)
#define VBOXVMM_INSTR_VMX_VMREAD_ENABLED() (0)
#define VBOXVMM_INSTR_VMX_VMRESUME(...) do { } while (0)
#define VBOXVMM_INSTR_VMX_VMRESUME_ENABLED() (0)
#define VBOXVMM_INSTR_VMX_VMWRITE(...) do { } while (0)
#define VBOXVMM_INSTR_VMX_VMWRITE_ENABLED() (0)
#define VBOXVMM_INSTR_VMX_VMXOFF(...) do { } while (0)
#define VBOXVMM_INSTR_VMX_VMXOFF_ENABLED() (0)
#define VBOXVMM_INSTR_VMX_VMXON(...) do { } while (0)
#define VBOXVMM_INSTR_VMX_VMXON_ENABLED() (0)
#define VBOXVMM_INSTR_WBINVD(...) do { } while (0)
#define VBOXVMM_INSTR_WBINVD_ENABLED() (0)
#define VBOXVMM_INSTR_WRMSR(...) do { } while (0)
#define VBOXVMM_INSTR_WRMSR_ENABLED() (0)
#define VBOXVMM_INSTR_XRSTORS(...) do { } while (0)
#define VBOXVMM_INSTR_XRSTORS_ENABLED() (0)
#define VBOXVMM_INSTR_XSAVES(...) do { } while (0)
#define VBOXVMM_INSTR_XSAVES_ENABLED() (0)
#define VBOXVMM_INSTR_XSETBV(...) do { } while (0)
#define VBOXVMM_INSTR_XSETBV_ENABLED() (0)
#define VBOXVMM_INT_HARDWARE(...) do { } while (0)
#define VBOXVMM_INT_HARDWARE_ENABLED() (0)
#define VBOXVMM_INT_SOFTWARE(...) do { } while (0)
#define VBOXVMM_INT_SOFTWARE_ENABLED() (0)
#define VBOXVMM_IPRT_CRITSECT_BUSY(...) do { } while (0)
#define VBOXVMM_IPRT_CRITSECT_BUSY_ENABLED() (0)
#define VBOXVMM_IPRT_CRITSECT_ENTERED(...) do { } while (0)
#define VBOXVMM_IPRT_CRITSECT_ENTERED_ENABLED() (0)
#define VBOXVMM_IPRT_CRITSECT_LEAVING(...) do { } while (0)
#define VBOXVMM_IPRT_CRITSECT_LEAVING_ENABLED() (0)
#define VBOXVMM_IPRT_CRITSECTRW_EXCL_BUSY(...) do { } while (0)
#define VBOXVMM_IPRT_CRITSECTRW_EXCL_BUSY_ENABLED() (0)
#define VBOXVMM_IPRT_CRITSECTRW_EXCL_ENTERED(...) do { } while (0)
#define VBOXVMM_IPRT_CRITSECTRW_EXCL_ENTERED_ENABLED() (0)
#define VBOXVMM_IPRT_CRITSECTRW_EXCL_ENTERED_SHARED(...) do { } while (0)
#define VBOXVMM_IPRT_CRITSECTRW_EXCL_ENTERED_SHARED_ENABLED() (0)
#define VBOXVMM_IPRT_CRITSECTRW_EXCL_LEAVING(...) do { } while (0)
#define VBOXVMM_IPRT_CRITSECTRW_EXCL_LEAVING_ENABLED() (0)
#define VBOXVMM_IPRT_CRITSECTRW_EXCL_LEAVING_SHARED(...) do { } while (0)
#define VBOXVMM_IPRT_CRITSECTRW_EXCL_LEAVING_SHARED_ENABLED() (0)
#define VBOXVMM_IPRT_CRITSECTRW_EXCL_WAITING(...) do { } while (0)
#define VBOXVMM_IPRT_CRITSECTRW_EXCL_WAITING_ENABLED() (0)
#define VBOXVMM_IPRT_CRITSECTRW_SHARED_BUSY(...) do { } while (0)
#define VBOXVMM_IPRT_CRITSECTRW_SHARED_BUSY_ENABLED() (0)
#define VBOXVMM_IPRT_CRITSECTRW_SHARED_ENTERED(...) do { } while (0)
#define VBOXVMM_IPRT_CRITSECTRW_SHARED_ENTERED_ENABLED() (0)
#define VBOXVMM_IPRT_CRITSECTRW_SHARED_LEAVING(...) do { } while (0)
#define VBOXVMM_IPRT_CRITSECTRW_SHARED_LEAVING_ENABLED() (0)
#define VBOXVMM_IPRT_CRITSECTRW_SHARED_WAITING(...) do { } while (0)
#define VBOXVMM_IPRT_CRITSECTRW_SHARED_WAITING_ENABLED() (0)
#define VBOXVMM_IPRT_CRITSECT_WAITING(...) do { } while (0)
#define VBOXVMM_IPRT_CRITSECT_WAITING_ENABLED() (0)
#define VBOXVMM_PDM_IRQ_GET(...) do { } while (0)
#define VBOXVMM_PDM_IRQ_GET_ENABLED() (0)
#define VBOXVMM_PDM_IRQ_HIGH(...) do { } while (0)
#define VBOXVMM_PDM_IRQ_HIGH_ENABLED() (0)
#define VBOXVMM_PDM_IRQ_HILO(...) do { } while (0)
#define VBOXVMM_PDM_IRQ_HILO_ENABLED() (0)
#define VBOXVMM_PDM_IRQ_LOW(...) do { } while (0)
#define VBOXVMM_PDM_IRQ_LOW_ENABLED() (0)
#define VBOXVMM_R0_GVMM_VM_CREATED(...) do { } while (0)
#define VBOXVMM_R0_GVMM_VM_CREATED_ENABLED() (0)
#define VBOXVMM_R0_HMSVM_VMEXIT(...) do { } while (0)
#define VBOXVMM_R0_HMSVM_VMEXIT_ENABLED() (0)
#define VBOXVMM_R0_HMVMX_VMEXIT(...) do { } while (0)
#define VBOXVMM_R0_HMVMX_VMEXIT_ENABLED() (0)
#define VBOXVMM_R0_HMVMX_VMEXIT_NOCTX(...) do { } while (0)
#define VBOXVMM_R0_HMVMX_VMEXIT_NOCTX_ENABLED() (0)
#define VBOXVMM_R0_VMM_RETURN_TO_RING3_HM(...) do { } while (0)
#define VBOXVMM_R0_VMM_RETURN_TO_RING3_HM_ENABLED() (0)
#define VBOXVMM_R0_VMM_RETURN_TO_RING3_NEM(...) do { } while (0)
#define VBOXVMM_R0_VMM_RETURN_TO_RING3_NEM_ENABLED() (0)
#define VBOXVMM_R0_VMM_RETURN_TO_RING3_RC(...) do { } while (0)
#define VBOXVMM_R0_VMM_RETURN_TO_RING3_RC_ENABLED() (0)
#define VBOXVMM_SVM_BUS_LOCK_THRESHOLD(...) do { } while (0)
#define VBOXVMM_SVM_BUS_LOCK_THRESHOLD_ENABLED() (0)
#define VBOXVMM_VMX_SPLIT_LOCK(...) do { } while (0)
#define VBOXVMM_VMX_SPLIT_LOCK_ENABLED() (0)
#define VBOXVMM_WHENEVER(...) do { } while (0)
#define VBOXVMM_WHENEVER_ENABLED() (0)
#define VBOXVMM_XCPT_AC(...) do { } while (0)
#define VBOXVMM_XCPT_AC_ENABLED() (0)
#define VBOXVMM_XCPT_BP(...) do { } while (0)
#define VBOXVMM_XCPT_BP_ENABLED() (0)
#define VBOXVMM_XCPT_BR(...) do { } while (0)
#define VBOXVMM_XCPT_BR_ENABLED() (0)
#define VBOXVMM_XCPT_DB(...) do { } while (0)
#define VBOXVMM_XCPT_DB_ENABLED() (0)
#define VBOXVMM_XCPT_DE(...) do { } while (0)
#define VBOXVMM_XCPT_DE_ENABLED() (0)
#define VBOXVMM_XCPT_DF(...) do { } while (0)
#define VBOXVMM_XCPT_DF_ENABLED() (0)
#define VBOXVMM_XCPT_GP(...) do { } while (0)
#define VBOXVMM_XCPT_GP_ENABLED() (0)
#define VBOXVMM_XCPT_MF(...) do { } while (0)
#define VBOXVMM_XCPT_MF_ENABLED() (0)
#define VBOXVMM_XCPT_NM(...) do { } while (0)
#define VBOXVMM_XCPT_NM_ENABLED() (0)
#define VBOXVMM_XCPT_NP(...) do { } while (0)
#define VBOXVMM_XCPT_NP_ENABLED() (0)
#define VBOXVMM_XCPT_OF(...) do { } while (0)
#define VBOXVMM_XCPT_OF_ENABLED() (0)
#define VBOXVMM_XCPT_PF(...) do { } while (0)
#define VBOXVMM_XCPT_PF_ENABLED() (0)
#define VBOXVMM_XCPT_SS(...) do { } while (0)
#define VBOXVMM_XCPT_SS_ENABLED() (0)
#define VBOXVMM_XCPT_SX(...) do { } while (0)
#define VBOXVMM_XCPT_SX_ENABLED() (0)
#define VBOXVMM_XCPT_TS(...) do { } while (0)
#define VBOXVMM_XCPT_TS_ENABLED() (0)
#define VBOXVMM_XCPT_UD(...) do { } while (0)
#define VBOXVMM_XCPT_UD_ENABLED() (0)
#define VBOXVMM_XCPT_VE(...) do { } while (0)
#define VBOXVMM_XCPT_VE_ENABLED() (0)
#define VBOXVMM_XCPT_XF(...) do { } while (0)
#define VBOXVMM_XCPT_XF_ENABLED() (0)
